linters-settings:
  gocognit:
    min-complexity: 45

  godox:
    keywords:
      - NOTE
      - BUG
      - HACK

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - goimports
    - funlen
    - maligned
    - gocyclo
    - gocognit
    - golint
    - lll
    - wsl
    - stylecheck
    - dupl
    - goconst
