// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bootstrap/protos/module.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValueType int32

const (
	ValueType_I32 ValueType = 0
	ValueType_I64 ValueType = 1
	ValueType_F32 ValueType = 2
	ValueType_F64 ValueType = 3
)

var ValueType_name = map[int32]string{
	0: "I32",
	1: "I64",
	2: "F32",
	3: "F64",
}

var ValueType_value = map[string]int32{
	"I32": 0,
	"I64": 1,
	"F32": 2,
	"F64": 3,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}

func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{0}
}

type Op int32

const (
	Op_Nop Op = 0
)

var Op_name = map[int32]string{
	0: "Nop",
}

var Op_value = map[string]int32{
	"Nop": 0,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{1}
}

type ModuleInfo struct {
	Types                []*FuncType       `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Functions            []*FuncInfo       `protobuf:"bytes,2,rep,name=functions,proto3" json:"functions,omitempty"`
	FuncImports          []*FuncImportInfo `protobuf:"bytes,3,rep,name=func_imports,json=funcImports,proto3" json:"func_imports,omitempty"`
	Tables               []*TableInfo      `protobuf:"bytes,4,rep,name=tables,proto3" json:"tables,omitempty"`
	Memories             []*MemoryInfo     `protobuf:"bytes,5,rep,name=memories,proto3" json:"memories,omitempty"`
	StartFunc            uint32            `protobuf:"varint,6,opt,name=start_func,json=startFunc,proto3" json:"start_func,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModuleInfo) Reset()         { *m = ModuleInfo{} }
func (m *ModuleInfo) String() string { return proto.CompactTextString(m) }
func (*ModuleInfo) ProtoMessage()    {}
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{0}
}

func (m *ModuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleInfo.Unmarshal(m, b)
}
func (m *ModuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleInfo.Marshal(b, m, deterministic)
}
func (m *ModuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleInfo.Merge(m, src)
}
func (m *ModuleInfo) XXX_Size() int {
	return xxx_messageInfo_ModuleInfo.Size(m)
}
func (m *ModuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleInfo proto.InternalMessageInfo

func (m *ModuleInfo) GetTypes() []*FuncType {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *ModuleInfo) GetFunctions() []*FuncInfo {
	if m != nil {
		return m.Functions
	}
	return nil
}

func (m *ModuleInfo) GetFuncImports() []*FuncImportInfo {
	if m != nil {
		return m.FuncImports
	}
	return nil
}

func (m *ModuleInfo) GetTables() []*TableInfo {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *ModuleInfo) GetMemories() []*MemoryInfo {
	if m != nil {
		return m.Memories
	}
	return nil
}

func (m *ModuleInfo) GetStartFunc() uint32 {
	if m != nil {
		return m.StartFunc
	}
	return 0
}

type FuncType struct {
	Params               []ValueType `protobuf:"varint,1,rep,packed,name=params,proto3,enum=ValueType" json:"params,omitempty"`
	Returns              []ValueType `protobuf:"varint,2,rep,packed,name=returns,proto3,enum=ValueType" json:"returns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FuncType) Reset()         { *m = FuncType{} }
func (m *FuncType) String() string { return proto.CompactTextString(m) }
func (*FuncType) ProtoMessage()    {}
func (*FuncType) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{1}
}

func (m *FuncType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncType.Unmarshal(m, b)
}
func (m *FuncType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncType.Marshal(b, m, deterministic)
}
func (m *FuncType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncType.Merge(m, src)
}
func (m *FuncType) XXX_Size() int {
	return xxx_messageInfo_FuncType.Size(m)
}
func (m *FuncType) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncType.DiscardUnknown(m)
}

var xxx_messageInfo_FuncType proto.InternalMessageInfo

func (m *FuncType) GetParams() []ValueType {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *FuncType) GetReturns() []ValueType {
	if m != nil {
		return m.Returns
	}
	return nil
}

type FuncImportInfo struct {
	Module               string   `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	TypeId               uint32   `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncImportInfo) Reset()         { *m = FuncImportInfo{} }
func (m *FuncImportInfo) String() string { return proto.CompactTextString(m) }
func (*FuncImportInfo) ProtoMessage()    {}
func (*FuncImportInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{2}
}

func (m *FuncImportInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncImportInfo.Unmarshal(m, b)
}
func (m *FuncImportInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncImportInfo.Marshal(b, m, deterministic)
}
func (m *FuncImportInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncImportInfo.Merge(m, src)
}
func (m *FuncImportInfo) XXX_Size() int {
	return xxx_messageInfo_FuncImportInfo.Size(m)
}
func (m *FuncImportInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncImportInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FuncImportInfo proto.InternalMessageInfo

func (m *FuncImportInfo) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *FuncImportInfo) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FuncImportInfo) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *FuncImportInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FuncInfo struct {
	TypeId               uint32       `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locals               []*LocalInfo `protobuf:"bytes,3,rep,name=locals,proto3" json:"locals,omitempty"`
	Code                 []*Operator  `protobuf:"bytes,4,rep,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FuncInfo) Reset()         { *m = FuncInfo{} }
func (m *FuncInfo) String() string { return proto.CompactTextString(m) }
func (*FuncInfo) ProtoMessage()    {}
func (*FuncInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{3}
}

func (m *FuncInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncInfo.Unmarshal(m, b)
}
func (m *FuncInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncInfo.Marshal(b, m, deterministic)
}
func (m *FuncInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncInfo.Merge(m, src)
}
func (m *FuncInfo) XXX_Size() int {
	return xxx_messageInfo_FuncInfo.Size(m)
}
func (m *FuncInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FuncInfo proto.InternalMessageInfo

func (m *FuncInfo) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *FuncInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FuncInfo) GetLocals() []*LocalInfo {
	if m != nil {
		return m.Locals
	}
	return nil
}

func (m *FuncInfo) GetCode() []*Operator {
	if m != nil {
		return m.Code
	}
	return nil
}

type TableInfo struct {
	Initial              uint32   `protobuf:"varint,1,opt,name=initial,proto3" json:"initial,omitempty"`
	Maximum              uint32   `protobuf:"varint,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	HasMaximum           bool     `protobuf:"varint,3,opt,name=has_maximum,json=hasMaximum,proto3" json:"has_maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableInfo) Reset()         { *m = TableInfo{} }
func (m *TableInfo) String() string { return proto.CompactTextString(m) }
func (*TableInfo) ProtoMessage()    {}
func (*TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{4}
}

func (m *TableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableInfo.Unmarshal(m, b)
}
func (m *TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableInfo.Marshal(b, m, deterministic)
}
func (m *TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableInfo.Merge(m, src)
}
func (m *TableInfo) XXX_Size() int {
	return xxx_messageInfo_TableInfo.Size(m)
}
func (m *TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TableInfo proto.InternalMessageInfo

func (m *TableInfo) GetInitial() uint32 {
	if m != nil {
		return m.Initial
	}
	return 0
}

func (m *TableInfo) GetMaximum() uint32 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *TableInfo) GetHasMaximum() bool {
	if m != nil {
		return m.HasMaximum
	}
	return false
}

type MemoryInfo struct {
	Initial              uint32   `protobuf:"varint,1,opt,name=initial,proto3" json:"initial,omitempty"`
	Maximum              uint32   `protobuf:"varint,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	HasMaximum           bool     `protobuf:"varint,3,opt,name=has_maximum,json=hasMaximum,proto3" json:"has_maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryInfo) Reset()         { *m = MemoryInfo{} }
func (m *MemoryInfo) String() string { return proto.CompactTextString(m) }
func (*MemoryInfo) ProtoMessage()    {}
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{5}
}

func (m *MemoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryInfo.Unmarshal(m, b)
}
func (m *MemoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryInfo.Marshal(b, m, deterministic)
}
func (m *MemoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryInfo.Merge(m, src)
}
func (m *MemoryInfo) XXX_Size() int {
	return xxx_messageInfo_MemoryInfo.Size(m)
}
func (m *MemoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryInfo proto.InternalMessageInfo

func (m *MemoryInfo) GetInitial() uint32 {
	if m != nil {
		return m.Initial
	}
	return 0
}

func (m *MemoryInfo) GetMaximum() uint32 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *MemoryInfo) GetHasMaximum() bool {
	if m != nil {
		return m.HasMaximum
	}
	return false
}

type LocalInfo struct {
	Count                uint32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Ty                   ValueType `protobuf:"varint,2,opt,name=ty,proto3,enum=ValueType" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LocalInfo) Reset()         { *m = LocalInfo{} }
func (m *LocalInfo) String() string { return proto.CompactTextString(m) }
func (*LocalInfo) ProtoMessage()    {}
func (*LocalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{6}
}

func (m *LocalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalInfo.Unmarshal(m, b)
}
func (m *LocalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalInfo.Marshal(b, m, deterministic)
}
func (m *LocalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalInfo.Merge(m, src)
}
func (m *LocalInfo) XXX_Size() int {
	return xxx_messageInfo_LocalInfo.Size(m)
}
func (m *LocalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LocalInfo proto.InternalMessageInfo

func (m *LocalInfo) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LocalInfo) GetTy() ValueType {
	if m != nil {
		return m.Ty
	}
	return ValueType_I32
}

type Operator struct {
	Op                   Op        `protobuf:"varint,1,opt,name=op,proto3,enum=Op" json:"op,omitempty"`
	Immediates           []uint64  `protobuf:"varint,2,rep,packed,name=immediates,proto3" json:"immediates,omitempty"`
	HasBlockTy           bool      `protobuf:"varint,3,opt,name=has_block_ty,json=hasBlockTy,proto3" json:"has_block_ty,omitempty"`
	BlockTy              ValueType `protobuf:"varint,4,opt,name=block_ty,json=blockTy,proto3,enum=ValueType" json:"block_ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_974bcf31bb27956e, []int{7}
}

func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_Nop
}

func (m *Operator) GetImmediates() []uint64 {
	if m != nil {
		return m.Immediates
	}
	return nil
}

func (m *Operator) GetHasBlockTy() bool {
	if m != nil {
		return m.HasBlockTy
	}
	return false
}

func (m *Operator) GetBlockTy() ValueType {
	if m != nil {
		return m.BlockTy
	}
	return ValueType_I32
}

func init() {
	proto.RegisterEnum("ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("Op", Op_name, Op_value)
	proto.RegisterType((*ModuleInfo)(nil), "ModuleInfo")
	proto.RegisterType((*FuncType)(nil), "FuncType")
	proto.RegisterType((*FuncImportInfo)(nil), "FuncImportInfo")
	proto.RegisterType((*FuncInfo)(nil), "FuncInfo")
	proto.RegisterType((*TableInfo)(nil), "TableInfo")
	proto.RegisterType((*MemoryInfo)(nil), "MemoryInfo")
	proto.RegisterType((*LocalInfo)(nil), "LocalInfo")
	proto.RegisterType((*Operator)(nil), "Operator")
}

func init() { proto.RegisterFile("bootstrap/protos/module.proto", fileDescriptor_974bcf31bb27956e) }

var fileDescriptor_974bcf31bb27956e = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6b, 0xdb, 0x4c,
	0x10, 0x8e, 0x3e, 0x62, 0x4b, 0xe3, 0xc4, 0xaf, 0xd9, 0xb7, 0xb4, 0xa2, 0xe0, 0xc6, 0x88, 0x96,
	0x98, 0x1c, 0x64, 0x90, 0x43, 0x6e, 0xbd, 0xe4, 0x10, 0x30, 0xd4, 0x35, 0x08, 0xd3, 0x43, 0x2f,
	0xee, 0x5a, 0x5a, 0x13, 0x11, 0x49, 0xbb, 0x48, 0x2b, 0xa8, 0xfa, 0x0b, 0xfa, 0x8b, 0x7b, 0x2e,
	0x3b, 0x2b, 0xc9, 0x36, 0xed, 0xb5, 0x27, 0xef, 0xf3, 0x31, 0x3b, 0xf3, 0xec, 0x18, 0xc1, 0x74,
	0xcf, 0xb9, 0xac, 0x64, 0x49, 0xc5, 0x42, 0x94, 0x5c, 0xf2, 0x6a, 0x91, 0xf3, 0xa4, 0xce, 0x58,
	0x80, 0xc8, 0xff, 0x65, 0x00, 0xac, 0x91, 0x58, 0x15, 0x07, 0x4e, 0x6e, 0xe0, 0x52, 0x36, 0x82,
	0x55, 0x9e, 0x31, 0xb3, 0xe6, 0xa3, 0xd0, 0x0d, 0x9e, 0xea, 0x22, 0xde, 0x36, 0x82, 0x45, 0x9a,
	0x27, 0xb7, 0xe0, 0x1e, 0xea, 0x22, 0x96, 0x29, 0x2f, 0x2a, 0xcf, 0x3c, 0x31, 0xa9, 0xf2, 0xe8,
	0xa8, 0x91, 0x10, 0xae, 0x14, 0xd8, 0xa5, 0xb9, 0xe0, 0xa5, 0xac, 0x3c, 0x0b, 0xbd, 0xff, 0x69,
	0x2f, 0x72, 0x58, 0x31, 0x3a, 0xf4, 0xb8, 0x22, 0x3e, 0x0c, 0x24, 0xdd, 0x67, 0xac, 0xf2, 0x6c,
	0x74, 0x43, 0xb0, 0x55, 0x10, 0x8d, 0xad, 0x42, 0x6e, 0xc1, 0xc9, 0x59, 0xce, 0xcb, 0x94, 0x55,
	0xde, 0x25, 0xba, 0x46, 0xc1, 0x5a, 0x11, 0x0d, 0xda, 0x7a, 0x91, 0x4c, 0x01, 0x2a, 0x49, 0x4b,
	0xb9, 0x53, 0x1d, 0xbc, 0xc1, 0xcc, 0x98, 0x5f, 0x47, 0x2e, 0x32, 0x6a, 0x04, 0x7f, 0x0b, 0x4e,
	0x97, 0x4d, 0xf5, 0x15, 0xb4, 0xa4, 0xb9, 0x8e, 0x3d, 0x0e, 0x21, 0xf8, 0x42, 0xb3, 0x9a, 0x61,
	0xee, 0x56, 0x21, 0xef, 0x61, 0x58, 0x32, 0x59, 0x97, 0x6d, 0xec, 0x73, 0x53, 0x27, 0xf9, 0x2f,
	0x30, 0x3e, 0x0f, 0x48, 0x5e, 0xc3, 0x40, 0x3f, 0xb8, 0x67, 0xcc, 0x8c, 0xb9, 0x1b, 0xb5, 0x88,
	0xbc, 0x82, 0xcb, 0x43, 0xca, 0xb2, 0xc4, 0x33, 0x91, 0xd6, 0x80, 0xbc, 0x81, 0xa1, 0x7a, 0xe7,
	0x5d, 0x9a, 0x78, 0x16, 0x4e, 0x3c, 0x50, 0x70, 0x95, 0x10, 0x02, 0x76, 0x41, 0x73, 0xe6, 0xd9,
	0xe8, 0xc6, 0xb3, 0xff, 0x43, 0x47, 0xc0, 0x36, 0x27, 0x85, 0xc6, 0x5f, 0x0b, 0xcd, 0x63, 0xa1,
	0xca, 0x9b, 0xf1, 0x98, 0x66, 0xdd, 0x56, 0x20, 0xf8, 0xa4, 0xa0, 0x7e, 0x67, 0xad, 0x90, 0x29,
	0xd8, 0x31, 0x4f, 0x58, 0xbb, 0x09, 0x37, 0xd8, 0x08, 0x56, 0x52, 0xc9, 0xcb, 0x08, 0x69, 0xff,
	0x1b, 0xb8, 0xfd, 0x6e, 0x88, 0x07, 0xc3, 0xb4, 0x48, 0x65, 0x4a, 0xb3, 0xb6, 0x79, 0x07, 0x95,
	0x92, 0xd3, 0xef, 0x69, 0x5e, 0xe7, 0x38, 0xc0, 0x75, 0xd4, 0x41, 0x72, 0x03, 0xa3, 0x67, 0x5a,
	0xed, 0x3a, 0x55, 0xa5, 0x75, 0x22, 0x78, 0xa6, 0xd5, 0x5a, 0x33, 0x3e, 0x05, 0x38, 0xee, 0xf5,
	0xdf, 0xb4, 0xf8, 0x08, 0x6e, 0x1f, 0x5c, 0x2d, 0x24, 0xe6, 0x75, 0x21, 0xdb, 0xfb, 0x35, 0x20,
	0x6f, 0xc1, 0x94, 0x0d, 0x5e, 0x7c, 0xbe, 0x71, 0x53, 0x36, 0xfe, 0x4f, 0x03, 0x9c, 0xee, 0x59,
	0xc8, 0xff, 0x60, 0x72, 0x81, 0xb5, 0xe3, 0xd0, 0x0a, 0x36, 0x22, 0x32, 0xb9, 0x20, 0xef, 0x00,
	0xd2, 0x3c, 0x67, 0x49, 0x4a, 0x25, 0xd3, 0xff, 0x1b, 0x3b, 0x3a, 0x61, 0xc8, 0x0c, 0xae, 0xd4,
	0x84, 0xfb, 0x8c, 0xc7, 0x2f, 0x3b, 0xd9, 0x9c, 0x8c, 0xf8, 0xa8, 0xa8, 0x6d, 0x43, 0x3e, 0x80,
	0xd3, 0xab, 0xf6, 0x1f, 0x53, 0x0c, 0xf7, 0xda, 0x76, 0xb7, 0x00, 0xb7, 0x67, 0xc9, 0x10, 0xac,
	0xd5, 0x32, 0x9c, 0x5c, 0xe0, 0xe1, 0xe1, 0x7e, 0x62, 0xa8, 0xc3, 0xd3, 0x32, 0x9c, 0x98, 0x78,
	0x78, 0xb8, 0x9f, 0x58, 0x77, 0xd7, 0x60, 0x6e, 0x84, 0x82, 0x9f, 0xb9, 0x98, 0x5c, 0x3c, 0x3a,
	0x5f, 0x07, 0xfa, 0xeb, 0xb0, 0xd7, 0xbf, 0xcb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x03,
	0x9f, 0xdc, 0x38, 0x04, 0x00, 0x00,
}
