(module
    (func (result i32)
        (block
            (i32.const 33)
            (drop)
            (i32.const 1)
            (br_if 0)
        )
        (block (result i32)
            (i32.const 42)
            (i32.const 1)
            (br_if 1)
            (drop)
            (i32.const 11)
        )
        (drop)
        (loop (result i32)
            (i32.const 0)
            (br_if 0)
            (i32.const 99)
        )
        return
    )
)